name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Executa a ação no push para a branch "main"

permissions:
  contents: write  # Necessário para publicar no GitHub Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Escolha a versão apropriada para o seu projeto

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Gera os arquivos estáticos na pasta "dist"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Diretório onde os arquivos estáticos são gerados
